### PR TITLE
Handling flat top-level routes

### LINKED ISSUE #33: _guessRoutePath throws error for non-nested routes.
_guessRoutePath(routeNames, name, index) {
    const routes = routeNames.slice(0, index + 1);

    if (routes.length === 1) {
      return `${name}.index`;
    } else {
      return routes.join('.');
    }
    },
throws this error: `Uncaught Error: Assertion Failed: [ember-crumbly] `route:examples.index` was not found` when in a pod format I have the perfectly legitimate `examples/route.js` `examples/template.hbs`.

### LINKED ISSUE #35: Assertion Failed: [ember-crumbly] `route:loading.index` was not found
This error is shown when I move from a page with ember-crumbly to a page without it.
The next page isn't loaded, so this error totally breaks the page navigation.
I don't have a loading route, but I have a `loading.hbs` template.

```
DEBUG: -------------------------------
ember.debug.js:4888 DEBUG: Ember                    : 1.12.0
ember.debug.js:4888 DEBUG: Ember Data               : 1.0.0-beta.18
ember.debug.js:4888 DEBUG: jQuery                   : 2.1.4
ember.debug.js:4888 DEBUG: Ember Simple Auth        : 0.8.0
ember.debug.js:4888 DEBUG: Ember Simple Auth Devise : 0.8.0
ember.debug.js:4888 DEBUG: -------------------------------
```

### LINKED ISSUE #50: Error: Assertion Failed: [ember-crumbly] `route:some-route.index` was not found
Happens, when there is no 'route'/index route setup in the project. Dunno if the pull request I created would work with 1.0.1 ? https://github.com/poteto/ember-crumbly/pull/34

### PR DESCRIPTION
**Pull request by gmurphey**
I'm not sure if this is the best implementation since you have to lookup the route twice if it's to the top-level route, but this will handle flat top-level routes (`route:about` if `route:about.index` doesn't exist, for example). 

Closes #33 
Closes #35
Closes #50

### CODE REVIEW

**Comment by gmurphey** [comment]
Travis failing due to issue fixed in #53

**Comment by poteto** [comment]
@homu retry

File: addon/components/bread-crumbs.js [hunk 1]
```diff
@@ -63,7 +64,15 @@ export default Component.extend({
     const routes = routeNames.slice(0, index + 1);
 
     if (routes.length === 1) {
-      return `${name}.index`;
+      let path = `${name}.index`;
+
+      if (this._lookupRoute(path)) {
+        return path;
+      } else {
+        warn(`[ember-crumbly] \`route:${path}\` was not found, falling back to \`route:${name}\``);
```
Comment (poteto) [inline addon/components/bread-crumbs.js]: I don't think this warning is necessary, might get annoying for apps that will only ever have flat routes

Comment (gmurphey) [inline addon/components/bread-crumbs.js]: That's true -- I'll take that out now!

**Comment by gmurphey** [comment]
That `warn` has been removed.

**Comment by poteto** [comment]
I think I'm OK with this approach for now. This addon is due for a bit of a refactor too, so I'm not too concerned about the double lookup. Thanks for this @gmurphey! I'm editing your PR description to close some reported issues.

**Comment by poteto** [comment]
@homu r+

**Comment by gmurphey** [comment]
@poteto happy to help! thanks for putting this together to begin with, it's been incredibly helpful!

**Comment by poteto** [comment]
:) I'm going to refactor this tomorrow before I do a release, hope that's OK!

**Comment by gmurphey** [comment]
No problem, looking forward to seeing it!

**Comment by scooterlord** [comment]
Hello! Is this going to be merged after all? :)
